# Generated by Django 4.2.6 on 2023-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(db_index=True, default='Dog product', max_length=30),
        ),
    ]
