# Generated by Django 4.2.6 on 2023-10-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('main_photo', models.ImageField(blank=True, upload_to='')),
                ('summary', models.TextField(blank=True, db_index=True, max_length=255)),
                ('content', models.TextField(blank=True, db_index=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_fucked', models.BooleanField(default=False)),
            ],
        ),
    ]
