# Generated by Django 4.2.6 on 2023-11-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Tag')),
                ('tag_slug', models.SlugField(max_length=20, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=75, unique=True, verbose_name='URL')),
                ('main_photo', models.ImageField(blank=True, upload_to='blog_photos/%Y/%m/%d', verbose_name='Main photo')),
                ('summary', models.TextField(db_index=True, max_length=255)),
                ('content', models.TextField(db_index=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='Blog.posttag')),
            ],
            options={
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='Blog_post_time_cr_113ab4_idx')],
            },
        ),
    ]
