# Generated by Django 4.2.6 on 2023-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_post_is_fucked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(db_index=True, max_length=255),
        ),
    ]
