# Generated by Django 4.2.6 on 2023-11-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='blog_photos/%Y/%m/%d', verbose_name='Main photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=75, unique=True, verbose_name='URL'),
        ),
    ]
