# Generated by Django 4.2.4 on 2023-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
