# Generated by Django 4.2.6 on 2023-11-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_post_main_photo_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Tag')),
                ('tag_slug', models.SlugField(max_length=20, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Blog.posttag'),
        ),
    ]
