# Generated by Django 4.2.4 on 2023-10-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_post_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, db_index=True, max_length=255),
        ),
    ]
