# Generated by Django 4.2.6 on 2024-02-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_post_blog_post_time_cr_113ab4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='Blog_post_search__47a33e_gin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='search_vector',
        ),
    ]
