# Generated by Django 4.2.6 on 2023-12-12 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=20)),
                ('product_slug', models.SlugField(unique=True)),
                ('product_price', models.FloatField(default=0.0)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_short_description', models.TextField(blank=True, db_index=True, max_length=30)),
                ('product_description', models.TextField(blank=True, db_index=True)),
                ('product_is_published', models.BooleanField(default=False)),
                ('product_type', models.CharField(db_index=True, max_length=30)),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photo', models.ImageField(upload_to='product_photos/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
            ],
        ),
    ]
