# Generated by Django 4.2.6 on 2024-01-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_content'),
        ('Shop', '0002_alter_product_related_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_post',
        ),
        migrations.AddField(
            model_name='product',
            name='related_post',
            field=models.ManyToManyField(blank=True, related_name='related_post', to='Blog.post'),
        ),
    ]
