# Generated by Django 4.2.6 on 2024-02-21 11:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def compute_search_vector(apps, schema_editor):
    product = apps.get_model("Shop", "Product")
    product.objects.update(search_vector=django.contrib.postgres.search.SearchVector(
        'product_name', 'product_short_description', 'product_description',
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_remove_product_related_post_product_related_post'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='Shop_produc_time_cr_88694c_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Shop_produc_search__6bfeaa_gin'),
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
