# Generated by Django 4.2.6 on 2023-12-14 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_product_product_main_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='product',
            name='time_create',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_main_photo',
            field=models.ImageField(default='Images/default_product_image.webp', upload_to='product_photos/%Y/%m/%d'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-time_create'], name='Shop_produc_time_cr_88694c_idx'),
        ),
    ]
