# Generated by Django 4.2.6 on 2023-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_product_options_product_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='product_photo',
            field=models.ImageField(blank=True, upload_to='product_photos/%Y/%m/%d'),
        ),
    ]
