# Generated by Django 4.2.6 on 2023-11-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_slug',
            field=models.SlugField(default='ss', unique=True),
            preserve_default=False,
        ),
    ]
