# Generated by Django 4.2.6 on 2023-11-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='static/Images/default_avatar.webp', upload_to='avatars/%Y/%m/%d', verbose_name='Avatar'),
        ),
    ]
