# Generated by Django 4.2.6 on 2024-01-12 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_usertheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='user_theme_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL),
        ),
    ]
